Traceback (most recent call last):
  File "tester.py", line 65, in <module>
ValueError: not enough values to unpack (expected 5, got 4)
[1165] Failed to execute script 'tester' due to unhandled exception!
Varificando data de envio...
PRAZO MÁXIMO: 2021-08-31T02:00:00-03:00
Testando sua solucao...
Procurando exercício 1...
Exercício 1...
